### ISSUE TITLE
[BUG] Verrouillage caractéristiques fiche personnage

### ISSUE THREAD

**Issue by sirchojin** [ariafrance/bugs#12]
**Description du bug**
Dans la feuille de personnage, les changements de flèches bas ou verrou des caractéristiques ne sont pas mémorisés à la fermeture de la fenêtre.

**Comment by Khyo-Aria** [comment]
Les stats ne montent pas non plus  -  Toujours a 20 et rien ne bouge

**Comment by sirchojin** [comment]
Résolu
