### ISSUE TITLE
[BUG] Ingrédient magique ne s'empile pas

### ISSUE THREAD

**Issue by Leefive20** [ariafrance/bugs#13]
Les ingrédients comme le moss, le ginseng, lemon grass etc.... ne s'empile pas dans notre sac a dos

**Comment by sirchojin** [comment]
A tester avec la nouvelle mise à jour de ce midi.

**Comment by sirchojin** [comment]
Je complète: le sac de 100 po de départ ne s'ajoute pas avec les autres sac de pièces d'or gagnées au cours du jeu.

**Comment by sirchojin** [comment]
Résolu au prochain redémarrage.
