### ISSUE TITLE
[BUG] Quete Blacksmith Part 1 :  Le metalsmith ne dits rien

### ISSUE THREAD

**Issue by Khyo-Aria** [ariafrance/bugs#14]
**Description du bug**
Quete Blacksmith Part 1 :  Le metalsmith ne dits rien , la quete ne demarre pas

**Reproduction du bug**
Etapes pour reproduire le bug:
1. Aller à '...' Ecran de profession
2. Cliquer sur '....' Demarrer
3. Parler a un Metalsmith 
4. rien ne se passe

**Comportement attendu**
Demarrage de la quete

**Captures d'écran**
![1](https://user-images.githubusercontent.com/53922875/62747671-85079880-ba23-11e9-9ad3-2c34cba6991a.jpg)
![2](https://user-images.githubusercontent.com/53922875/62747676-89cc4c80-ba23-11e9-91ff-a45dc80cab77.jpg)
![3](https://user-images.githubusercontent.com/53922875/62747679-8cc73d00-ba23-11e9-8778-d3f1121bb5cf.jpg)

**Informations additionnelles**
none

**Comment by sirchojin** [comment]
A tester avec la nouvelle mise à jour de ce midi.

**Comment by Khyo-Aria** [comment]
Pas de changements,  j ai teste toutes les possibilites de dialogue , je vois rien qui peut demarrer la quete

**Comment by Khyo-Aria** [comment]
oups

**Comment by sirchojin** [comment]
Ok merci ! Résolu.
