### ISSUE TITLE
[BUG] taming des bat

### ISSUE THREAD

**Issue by jimmyyyy8** [ariafrance/bugs#16]
le taming des bat demande avoir tout ses slots créature de libre a 0/5 pour taming des bat même si la bat demende un slots

**Comment by sirchojin** [comment]
Merci de respecter le format de la demande de bug.
J'ai besoin d'une capture d'écran également concernant le message exact.

**Comment by sirchojin** [comment]
A réessayer. Pas eu de soucis sur le sujet.

**Comment by Leefive20** [comment]
Toujours le même soucis pour le taming d'un bat dans black forest il demande que tout tes slots sois vide j'ai du abandonné mon cheval

**Comment by kylaora** [comment]
Chojin il manque : `<DoubleVariable Name="PetSlots">1</DoubleVariable> `dans le template du bat.xml
