### ISSUE TITLE
bug affichage après résurrection

### ISSUE THREAD

**Issue by Leefive20** [ariafrance/bugs#2]
Après la mort de mon cheval, je l'ai résurrrect avec bandage et son nom s'affichait comme suis : Corps de cheval j'ai du le renommé pour qu'il perde ce titre

![image](https://user-images.githubusercontent.co
![Sans titre](https://user-images.githubusercontent.com/53791734/62483456-af3c2a80-b785-11e9-9024-3cc1f31a7060.png)
m/53791734/62483361-6c7a5280-b785-11e9-84d6-aa4a47edd336.png)

**Comment by sirchojin** [comment]
Soucis dans le script de gestion de la mort.
C'est corrigé.
A tester de nouveau.

**Comment by sirchojin** [comment]
Résolu.
