### ISSUE TITLE
[BUG] Crafts carpentry manquants

### ISSUE THREAD

**Issue by Regdod** [ariafrance/bugs#21]
**Description du bug**
Des crafts carpentry ne figurent pas dans le menu

**Reproduction du bug**
Ouvrir le menu de crafting à partir d'une carpentry table, onglet Furnishings > Tables & Chairs 

**Comportement attendu**
Ajouter : 
Wooden Chair
Wooden Tables
Fancy Chair
Large Wooden Tables
Fancy Bench
Round Table 
Inn Table
Fancy Desk

**Informations additionnelles**
Des craft orders pour ces objets sont accessibles.
A déterminer : est-ce qu'un joueur qui a appris la recette pour fabriquer un de ces objets listés l'a bien mémorisée ou devra-t'il l'apprendre après correction du bug

**Comment by sirchojin** [comment]
Bug de catégorie. Résolu.
