### ISSUE TITLE
[BUG] La musique en harmonie ne se déclenche pas

### ISSUE THREAD

**Issue by MrWinstonW0LF** [ariafrance/bugs#22]
**Description du bug**
Lorsqu'on lance la compétence pour jouer de la musique en groupe après avoir déjà joué auparavant, on n'entend qu'un seul instrument, voir pas d'instrument du tout.
Ce bug ne semble pas affecter les autres joueurs qui écoutent, seulement le musicien.

**Reproduction du bug**
Etapes pour reproduire le bug:
1. Faire un groupe avec un joueur en train de jouer d'un instrument.
2. Lancer la musique avec la compétence.
2. Interrompre la compétence pour arrêter de jouer de la musique.
3. Relancer la même compétence pour jouer de la musique à nouveau.
4. On n'entend plus l'instrument de l'autre membre du groupe. Parfois même notre propre instrument est silencieux.

**Comportement attendu**
Lorsqu'on lance la compétence, la musique devrait jouer en harmonie avec les autres instruments.

**Comment by sirchojin** [comment]
Ne sera pas traité, bug du client et/ou côté Citadel.
