### ISSUE TITLE
[BUG] Ajout de marqueur sur map

### ISSUE THREAD

**Issue by glaenix** [ariafrance/bugs#23]
**Description du bug**
lorsque l'on souhaite ajouter un marqueur sur l'atlas (avec la carte de la région), le marqueur ne se pose pas là où est notre pointeur mais se met en haut de l'atlas.

**Reproduction du bug**
Etapes pour reproduire le bug:
1. Ouvrir l'Atlas
2. Cliquer pour ajouter un marqueur
3. Renseigner le marqueur
4. Le marqueur ne sera pas là où vous l'avait créé.

**Comportement attendu**
Que le marqueur soit créer à l'emplacement du pointeur.

**Captures d'écran**
https://image.noelshack.com/fichiers/2019/32/7/1565507691-atlas-2.png
https://image.noelshack.com/fichiers/2019/32/7/1565507696-atlas.png

**Informations additionnelles**
Mettre ici toute autre information utile.

**Comment by sirchojin** [comment]
Je n'ai pas réussi à reproduire le problème.
Peux-tu réessayer : 
- Ouvrir l'Atlas
- Zoomer sur ta région
- Ajouter un marqueur
- Fermer l'Atlas
- Ouvrir de nouveau l'Atlas
- Le marque est-il toujours en haut bêtement ?
- Lorsque tu zoomes sur la région, vois-tu le marque à la bonne place ?

Si toujours non fonctionnel je regarderai avec toi ton Atlas, peut-être a-t-il un bug.

**Comment by glaenix** [comment]
oui toujours le même problème...
le marqueur part en haut bêtement et lorsque je zoom il n'est pas là où je souhaite qu'il soit

**Comment by sirchojin** [comment]
Pas réussi à reproduire le bug.
J'attends d'autres retours.

**Comment by kylaora** [comment]
Bug reproduit : Corrigé dans mon commit de ce jour à tester avant mise en production
