### ISSUE TITLE
Quête de pêcheur bug

### ISSUE THREAD

**Issue by Leefive20** [ariafrance/bugs#25]
J'ai accepté le début de la quête pour les pêcheurs, par contre rendu a Catch a fish

1. Aller à Pyro's landing
2. Cliquer sur un NPC avec l'icone d'une hameçon de pêche puis débuté la quête fishing
3. Défiler les quêtes jusqu'à Catch a fish
4. après l'avoir abandonné et reprise plusieurs fois et avoir pêcher au moins 500 poissons elle ne ce termine pas

**Comment by sirchojin** [comment]
A tester de nouveau.
Il faut aussi le nom exact de la quête ;)

**Comment by sirchojin** [comment]
Fixé.
