### ISSUE TITLE
[BUG] Mission Ork in Valus

### ISSUE THREAD

**Issue by Leefive20** [ariafrance/bugs#26]
J'ai fait 4 missions Ork in Valus 2x, East Valusia, West Valusia

Etapes pour reproduire le bug:
1. Aller à Toby le dispatcher
2. Cliquer sur une des missions qu'il vous offre
3. ce rendre sur les lieux de la mission
4. À mon arrivé 2 X sur les 4 tentative la tente n'étais pas possible à détruire, lorsque je drag sa vie il était écrit UNknown et je ne pouvais lui faire aucun dégât. lorsque la quête ne bug pas je peux drag sa vie et elle porte le nom de Ork tent et je vois la vie baisser.

**Comportement attendu**
Une description clair et concise de ce que vous attendez comme comportement à la place, ou comme action, comme texte, etc.

**Captures d'écran**
Malheureusement je n'ai pas pensé faire une capture d'écran

**Comment by MeganHaelys** [comment]
Salut Leefive, ca m'est arrivé a plusieurs reprises aussi. Tu peux tout de meme tuer le truc de quest, ca mest arrivé souvent, tu ne vois pas le damage que tu lui fais, mais pourtant ca marche.
![20190812200621_1](https://user-images.githubusercontent.com/54011804/62906503-f6558d00-bd3c-11e9-98fe-89466daa1cdc.jpg)

![20190812200754_1](https://user-images.githubusercontent.com/54011804/62906505-f8b7e700-bd3c-11e9-8c7c-b724560bcd6a.jpg)

J'ai pris le 2ieme screenshot un peu late et on na pas pu voir la Reward, mais ca la bien poppé dans mon ecran :)

**Comment by glaenix** [comment]
Salut, ça me l'a fait aussi plusieurs fois . Solution simple : fermer le jeu et le réouvrir, cela te prends 10 secondes à faire et te permet de revoir la santé de l'objet et de pouvoir voir sa vie descendre lorsque tu le frappes. Cependant même si tu as l'impression de ne pas le détruire, il encaisse toujours les dégâts et disparaîtra au moment où ses HP tomberont à 0 donc à toi de voir.

**Comment by sirchojin** [comment]
Missions Ork désactivées pour le moment.
