### ISSUE TITLE
[BUG] Quete The Dead Rise, incapable de l'accomplir?

### ISSUE THREAD

**Issue by MeganHaelys** [ariafrance/bugs#27]
Je parle au NPC qu'ils me disent de parler et ca ne marche pas... Je sais pas si la quest n'est juste pas programmé encore ou s'il manque quelque chose?
Voici 3 screenshots montrant le dialogue avec le NPC en question?

![The Dead Rise 1](https://user-images.githubusercontent.com/54011804/62843053-f5612480-bc84-11e9-9e04-942bd5b54162.png)
![The Dead Rise 2](https://user-images.githubusercontent.com/54011804/62843056-fabe6f00-bc84-11e9-8cc1-b76c17a570e7.png)
![The Dead Rise 3](https://user-images.githubusercontent.com/54011804/62843059-fd20c900-bc84-11e9-979b-6a72f39015ed.png)

**Comment by sirchojin** [comment]
La quête n'est effectivement pas finie.
Je ferme pour l'instant.
On va attendre un fix de Citadel.
