### ISSUE TITLE
[BUG] archerie

### ISSUE THREAD

**Issue by Lynius** [ariafrance/bugs#28]
**Description du bug**
Il y a des problemes de pause lors du tir sans mouvemement, et c'est compliqué de faire arreter le tir en continu.

**Reproduction du bug**
Essayer de courir lors du tir en continu ou bien rester sans bouger et voir que parfois des "pauses" dans le tir en continu ont lieu.

**Comportement attendu**
Aucune pause dans le tir en continue lorsque l'on ne bouge pas, et par contre lorsque l'on veut courir une fois la barre de "rechargement" de fleche finit, pouvoir courir a nouveau et que cela stop le tir en continu.

**Captures d'écran**
Il faudrait une video d'ecran :D

**Informations additionnelles**
Mettre ici toute autre information utile.

**Comment by sirchojin** [comment]
A tester avec le nouveau patch du 16/08/2019.
