### ISSUE TITLE
Vitesse d'attaque des arcs

### ISSUE THREAD

**Issue by Lynius** [ariafrance/bugs#29]
**Description du bug**
La vitesse d'attaque du Short Bow devrait etre de 2 hors il est de 2.5. (c'est peut etre pareil pour les autres arc.)

**Reproduction du bug**
Passer le curseur sur un short bow ou bien l'equiper.

**Comportement attendu**
Avoir une vitesse de 2.

**Captures d'écran**
https://steamcommunity.com/sharedfiles/filedetails/?id=1832364018

**Informations additionnelles**
Mettre ici toute autre information utile.

**Comment by sirchojin** [comment]
Réglé.
