### ISSUE TITLE
Karma 

### ISSUE THREAD

**Issue by Leefive20** [ariafrance/bugs#3]
j'ai tué un joueur bleu et suis resté bleu, a -3000 de Karma et je ne peux pas le résurrect ni soigné il me dit que je perdrais du Karma. je ne peux pas non plus revenir orange ou rouge avec le karma dans le paperdoll . 
le système de mort semble mal implanté puisque nous ne pouvons rien faire lorsque mort aucun ghost ou affichage qui apparait un personnage de même karma (lorsqu'on est rouge) peut nous résurrect seulement.
 j'ai également accès à la ville de Valus en temps que meurtrier
Bref il y aura beaucoup de travail et de test à faire côté PVP 

![Red in town](https://user-images.githubusercontent.com/53791734/62486301-e7933700-b78c-11e9-8d0d-4a64f6bcb923.png)
![dead](https://user-images.githubusercontent.com/53791734/62486317-ed891800-b78c-11e9-974f-6bff6b362315.png)

**Comment by sirchojin** [comment]
Le système de Karma a été corrigé. Merci de tester à nouveau.

**Comment by sirchojin** [comment]
Résolu.
