### ISSUE TITLE
[BUG] Gourde : fill ne fonctionne pas 

### ISSUE THREAD

**Issue by Regdod** [ariafrance/bugs#30]
**Description du bug**
Le bouton fill de la gourde ne fonctionne pas. Il faut utiliser le bouton use.

**Reproduction du bug**
Clic droit sur une gourde
Fill

**Comportement attendu**
Fill doit permettre de remplir la gourde
Use doit permettre d'arroser lorsque la gourde est remplie

**Comment by sirchojin** [comment]
A tester de nouveau suite au patch ;)
