### ISSUE TITLE
[BUG] Annulation attaque si dégât subit

### ISSUE THREAD

**Issue by glaenix** [ariafrance/bugs#35]
**Description du bug**
Lorsqu'il y a plusieurs mobs qui nous attaque, le cycle d'auto-attaque (déterminé par la vitesse de l'arme : chez moi 3.25s) peut être annulé à cause de l'animation de prise de dégât subit. Ce qui fait que pendant X seconde on ne peux plus attaquer voir plus attaquer du tout si trop de mob. Donc au delà de 2 mobs c'est presque impossible d'attaquer avec l'auto attaque.

**Reproduction du bug**
Etapes pour reproduire le bug:
1. Se battre contre 3 mobs minimum (c'est flagrant)
2. Attaquer normalement sans skill en connaissant son cycle de DPS (vitesse)
3. compter et voir si on attaque bien toutes les X secondes (vitesse arme)
4. Observer que notre personnage n'attaque plus

**Comportement attendu**
Que l'on puisse continuer à attaquer même en se prenant des DPS constant. On a une armure c'est pour encaisser sans broncher normalement.

**Captures d'écran**
Si possible faites des captures d'écrans pour mieux illustrer votre problème.

**Informations additionnelles**
Mettre ici toute autre information utile.

**Comment by sirchojin** [comment]
A tester avec le nouveau patch du 16/08/2019.
