### ISSUE TITLE
[BUG] URGENT - Absence de backpack à la création du personnage

### ISSUE THREAD

**Issue by Regdod** [ariafrance/bugs#36]
**Description du bug**
Absence de backpack à la création du personnage

**Reproduction du bug**
Créer un nouveau personnage. 
Absence du backpack aux pieds sur le paperdoll.
Touche B inefficace 

**Informations additionnelles**
Bug suite patch sur la faim > pain attribué aux nouveaux joueurs ?

**Comment by sirchojin** [comment]
Résolu.
