### ISSUE TITLE
[BUG] pas possible de looter avec right click

### ISSUE THREAD

**Issue by Khyo-Aria** [ariafrance/bugs#38]
**Description du bug**
Durant l event a corruption , le gros ours de Joseph etais au dessus de mon corps
j ai pas reussi a le looter

.

**Captures d'écran**
![8](https://user-images.githubusercontent.com/53922875/63201682-52c5ee80-c054-11e9-9821-ea2fb1770d79.jpg)

Meme avec CTRL  j ai pas la possibilite de looter

**Comment by Khyo-Aria** [comment]
j ai du attendre que l ours disparaisse pour pouvoir looter mon corps.  j ai l intention de demander des dommages et interets si j ai attrape la grippe !!!!

**Comment by sirchojin** [comment]
Bug du jeu en lui même. Je ne peux rien faire.
