### ISSUE TITLE
[BUG] Entertainement n'apparait pas dans laa liste des compétences lors de la création d'un personnage 

### ISSUE THREAD

**Issue by kylaora** [ariafrance/bugs#4]
**Description du bug**
Entertainment n'apparait pas dans la liste des skills

**Reproduction du bug**
création de personnage et choix d'un skill dans la liste

**Comportement attendu**
la ligne avec entertainment devrait apparaitre

**Captures d'écran**
Si possible faites des captures d'écrans pour mieux illustrer votre problème.

**Comment by sirchojin** [comment]
Résolu.
