### ISSUE TITLE
[BUG] impossibilité de passer compagnon fighter

### ISSUE THREAD

**Issue by glaenix** [ariafrance/bugs#40]
**Description du bug**
Lors de la quête pour passer compagnon fighter et après avoir parler au grandmaster, celui ci nous demande de réaliser une mission mais la quête ne se lance pas.
**Reproduction du bug**
Etapes pour reproduire le bug:
1.  Parler à Kato à eldeir
2. avoir les prérequis pour être compagnon fighter
3. Accepter de devenir compagnon et l'entendre dire : revenez quand vous aurez accompli la mission
4. Voir dans les quêtes qu'il faut toujours parler à Kato...donc boucle.

**Comportement attendu**
Qu'il y ai la suite de la quête pour  être compagnon fighter

**Captures d'écran**
Si possible faites des captures d'écrans pour mieux illustrer votre problème.

**Informations additionnelles**
Mettre ici toute autre information utile.

**Comment by Khyo-Aria** [comment]
meme probleme ici   Kato marche pas
Par contre sur les serveurs officiels , des que je me suis logge j ai recu   Tome : Journeyman Fighter.  Je suis pas sur mais il me semble que j avais vu ce message sur Aria France pendant la quete mais rien en inventaire

![10](https://user-images.githubusercontent.com/53922875/63225756-ca556400-c1a1-11e9-82c5-54aea6dc5eee.jpg)
![11](https://user-images.githubusercontent.com/53922875/63225757-d0e3db80-c1a1-11e9-802c-b6006a1c4203.jpg)

**Comment by Khyo-Aria** [comment]
j ai abandonne la quete et recommencer 
Apres l etape des liches  je recois la Tome of journeyman fighter  et il m envoie voir Kato a Eilder
![12](https://user-images.githubusercontent.com/53922875/63225848-21a80400-c1a3-11e9-93ae-b7a1b7e4153a.jpg)

et a Eilder  Kato  le prends et ...  rien

![13](https://user-images.githubusercontent.com/53922875/63225868-6469dc00-c1a3-11e9-869a-bb98eb44f40a.jpg)

![14](https://user-images.githubusercontent.com/53922875/63225883-90855d00-c1a3-11e9-9be0-c9acdbe7ec15.jpg)

**Comment by sirchojin** [comment]
A tester avec le patch de lundi.

**Comment by Khyo-Aria** [comment]
non

**Comment by Khyo-Aria** [comment]
le patch de 21 aout a fixe le probleme   merci Chojin

**Comment by sirchojin** [comment]
Fixé.
