### ISSUE TITLE
[FEATURE] Renommer les sacoches

### ISSUE THREAD

**Issue by Elihora** [ariafrance/bugs#42]
Une suggestion pour le serveur (si réalisable techniquement) : avoir la possibilité de renommer les sacoches que l'on crafte afin de pouvoir mieux organiser son inventaire. 

Ex : Sac de graines, Sac à provision, etc.

**Comment by Khyo-Aria** [comment]
![image](https://user-images.githubusercontent.com/53922875/63227427-756f1900-c1b4-11e9-9609-3c33f1853264.png)

**Comment by sirchojin** [comment]
Fait.
