### ISSUE TITLE
[Feature] retirer le filtre de langague

### ISSUE THREAD

**Issue by Elihora** [ariafrance/bugs#43]
Sacoche d'ingrédients est censuré.
Tous les mots contenant "con" sont censuré.

Je propose de lever/alléger le filtre car il est très compliqué de pouvoir écrire des parchemins IG, renommer des sac etc. 

Merci d'avance !

**Comment by sirchojin** [comment]
J'a allégé le filtre, prise en compte pour le patch de lundi.
