### ISSUE TITLE
[BUG] Blacksmithing

### ISSUE THREAD

**Issue by Khyo-Aria** [ariafrance/bugs#45]
**Description du bug**
Le Quaterstaff  est dans la liste des armes de type bashing  ,  mais une fois fabrique, c est une arme de categorie Lancing

![15](https://user-images.githubusercontent.com/53922875/63278721-d01c7980-c275-11e9-9cb0-f0f05eb4f15f.jpg)

Sur les training Dummy ca donne rien en bashing donc  je suppose que c est bien du lancing

et je me doute que ca viens de l officiel ;-p

**Comment by sirchojin** [comment]
Fixé.
