### ISSUE TITLE
[BUG] Recette superbe boites a musique

### ISSUE THREAD

**Issue by ghost** [ariafrance/bugs#46]
**Description du bug**
Incapable d'apprendre la recette.

**Reproduction du bug**
Etapes pour reproduire le bug:
1. Avoir la recette sur soit
2. Double cliquer sur elle
3. Affiche "Vous ne pouvez réapprendre cette recette"

**Comportement attendu**
Puisqu'a prime abord je ne connais pas cette recette, je m'attend a l'apprendre en double cliquant. Pour pourvoir la construire ensuite.

**Informations additionnelles**
Le bug n'est pas juste pour moi, j'ai partager la recette avec Joseph et le résultat est le même

**Comment by sirchojin** [comment]
Fixé.

**Comment by ghost** [comment]
je ne peux toujours pas l'apprendre!

**Comment by ghost** [comment]
25 Aout 2019 je vien de recevoir a nouveau la recette de Superbe boites a musique et encore une fois je ne peu l'apprendre
