### ISSUE TITLE
Arrêt du tir auto de l'archer

### ISSUE THREAD

**Issue by Lynius** [ariafrance/bugs#49]
**Description du bug**
Lorsque l'on réussit a se soigner avec un bandage le tir automatique de l'archer s’arrête automatiquement et il nous faut le réactiver.

**Reproduction du bug**
1-Activer le tir auto
2-Lancer un bandage
3-Réussir a l'appliquer
4-Le tir auto est normalement désactiver

**Comportement attendu**
Que le tir auto ne se désactive pas a la réussite d’application d'un bandage.

**Captures d'écran**
Si possible faites des captures d'écrans pour mieux illustrer votre problème.

**Informations additionnelles**
Mettre ici toute autre information utile.

**Comment by sirchojin** [comment]
C'est le fonctionnement attendu. Comme le guerrier. On ne veut pas que les joueurs se heal en continu avec un bandage et continuer à combattre comme si de rien n'était.
