### ISSUE TITLE
[Bug] Aucun coffre dans hall of comtempt.

### ISSUE THREAD

**Issue by Lynius** [ariafrance/bugs#51]
**Description du bug**
Aucun coffre dans hall of comtempt.

**Reproduction du bug**
Aller a hall of contempt et voir aucun coffre

**Comportement attendu**
Avoir quelque coffre a ouvrir avec la competence lockpiking

**Captures d'écran**
Si possible faites des captures d'écrans pour mieux illustrer votre problème.

**Informations additionnelles**
Mettre ici toute autre information utile.

**Comment by sirchojin** [comment]
Les donjons ont été revamp suite à la dernière MaJ Citadel. A retester.
