### ISSUE TITLE
Pas d’arrêt du combat automatique du guerrier après un bandage réussit.

### ISSUE THREAD

**Issue by Lynius** [ariafrance/bugs#52]
**Description du bug**
Pas d’arrêt du combat automatique du guerrier après un bandage réussit.

**Reproduction du bug**
Reussir a s'appliquer un bandage

**Comportement attendu**
Sortir de combat apres l'application d'un bandage.
**Captures d'écran**
Si possible faites des captures d'écrans pour mieux illustrer votre problème.

**Informations additionnelles**
Mettre ici toute autre information utile.

**Comment by sirchojin** [comment]
Comportement attendu.
