### ISSUE TITLE
[BUG] Bandage et autofire de l'archer

### ISSUE THREAD

**Issue by sirchojin** [ariafrance/bugs#53]
**Description du bug**

Il y a aussi un bug avec l autofire de l'archer
- Si tu réussis à faire ton bandage l'autofire se stoppe.
- Par contre si tu es interrompu l'autofire reste actif donc tu continues à attaquer.

**Comment by kylaora** [comment]
Pour moi pas de Bug :
Résumé du fonctionnement actuel :
1 j'attaque une cible en autofire
2 je me heal puis je bouge cela annule le bandage =>Autofire reste actif
3 Je me heal mais je laisse le bandage s'activé =>autofire Off
