### ISSUE TITLE
[BUG] Overload du sac possible en ramassant du coton

### ISSUE THREAD

**Issue by kylaora** [ariafrance/bugs#56]
**Description du bug**
Le poid max du backpack peut etre dépassé en ramassant du coton

**Reproduction du bug**
Etapes pour reproduire le bug:
Ramasser du coton jusqu'à l'overload

**Comportement attendu**
Avoir un message comme quoi je ne peux pas ramassé cela car mon sac est surchargé

**Captures d'écran**
![image](https://user-images.githubusercontent.com/53836790/63647876-da33f180-c727-11e9-9c45-ba21c822ffa4.png)

**Informations additionnelles**
Mettre ici toute autre information utile.

**Comment by ghost** [comment]
Pas que le coton, tout les composants qui se recolte en forest, lemon grass, moss, ginsen, mushroom!

**Comment by sirchojin** [comment]
Fixé.
