### ISSUE TITLE
[BUG] Competence Journeyman Fighter - DART - fonctionne plus 

### ISSUE THREAD

**Issue by Khyo-Aria** [ariafrance/bugs#57]
**Description du bug**
Pas assez de competence pour utiliser cette capacite

![18](https://user-images.githubusercontent.com/53922875/63652038-a9ed5280-c729-11e9-9ef1-37427c93c778.jpg)

**Comment by sirchojin** [comment]
Et tes compétences sont de ?

**Comment by Khyo-Aria** [comment]
celle que tu achetes avec le prestige   Dart  10% running speed pour 10 sec 
Ca marchais avant le roll back

**Comment by sirchojin** [comment]
Tu as la profession Rogue ?

**Comment by Khyo-Aria** [comment]
non  mais c est disponible pour les 2  fighters  et rogue

**Comment by Khyo-Aria** [comment]
![19](https://user-images.githubusercontent.com/53922875/63655239-bd151800-c753-11e9-83ab-b37e7355bba5.jpg)

**Comment by sirchojin** [comment]
Bizarre, résolu magiquement. Je ferme.
