### ISSUE TITLE
[BUG] quêtes de combat

### ISSUE THREAD

**Issue by Elihora** [ariafrance/bugs#58]
**Description du bug**
j'ai noté que ça fait deux fois que j'ai un bug au niveau de la quête de combat qui demande de détruire les cavernes d'ours. La caverne a une barre de vie fixe sur l'écran, quand on glisse la barre de vie pour la suivre c'est indiqué unknow et elle reste vide (cf. screen). La quête se valide cependant à force de taper dessus, mais la caverne reste visible en jeu
![20190825173558_1](https://user-images.githubusercontent.com/54242141/63652321-68779a00-c75f-11e9-8bfa-38f8c3dd7c0e.jpg)
.

**Reproduction du bug**
Prendre une mission de combat concernant les ours je suppose.

**Comportement attendu**
Rendre à la mission son comportement normal

**Captures d'écran**
Cf. Description du problème

**Informations additionnelles**
Merci d'avance !

**Comment by sirchojin** [comment]
Je garde ouvert mais à priori c'est un bug côté Citadel.

**Comment by sirchojin** [comment]
Revamp suite à la dernière MaJ Citadel. A retester.
