### ISSUE TITLE
[BUG] Impossible de grouper à plus de deux

### ISSUE THREAD

**Issue by Elihora** [ariafrance/bugs#67]
Impossible de grouper à plus de deux. On a tenté toutes les combinaisons de duo mais impossible de grouper les trois joueurs présents. Est-ce lié au client expérimental ? 

**Comportement attendu**
Pourvoir grouper à plus de deux !

**Informations additionnelles**
Joueurs concernés (si le bug vient d'un perso) : Celebrin Labeur, OcxZ Hemingway et Nerys

**Comment by sirchojin** [comment]
A tester de nouveau.
