### ISSUE TITLE
[BUG] Différents problèmes sur la minimap

### ISSUE THREAD

**Issue by kylaora** [ariafrance/bugs#7]
**Description du bug**
Probleme de visualisation d'icone et de superposition des menus
1 - Icone carré en haut à droite => Icone PVP désactivé ? [https://screenpresso.com/=N0skc](url)
2 - superposition du menu de parametre avec le nom de la ville rend le texte illisible [https://screenpresso.com/=pitTb](url) Solution mettre un z-index superieur au nom de la ville et ne pas avoir le fond transparent
3 - l'infobulle de l'icone de la map globale passe en dessous de l'icone des parametres [https://screenpresso.com/=m1Meb](url) Solution soit le faire afficher au dessus de l'icone soit modifier sont z-index pour etre supérieur à ccelui du bouton parametres 
4 - Même soucis que le 3 pour les infobulles des icones des endroits sur la minimap

**Comment by sirchojin** [comment]
Résolu
