### ISSUE TITLE
[BUG] Missions "league of Procurers" KO

### ISSUE THREAD

**Issue by RoseVespa** [ariafrance/bugs#72]
**Description du bug**
Impossible de terminer les missions à la "league of Procurers".
A la dernière étape, à savoir retourner voir Naldren pour lui remettre ce qu'il a commandé (bois, recette, etc...), il :
- prend bien l'objet de la mission, 
- la phrase liée à la mission disparaît bien dans les interactions avec Naldren,
mais :
- la seconde étape de la mission "give ... to Naldren in Valus" reste affichée
- les 100 points de récompense ne sont pas attribués

**Capture d'écran**
https://cdn.discordapp.com/attachments/519658845375561738/704769113184010340/unknown.png

**Informations additionnelles**
Les missions dans les ligues sans cette seconde étape "retourner voir machin" fonctionnent bien et incrémentent les points de récompenses. 
Je n'ai malheureusement pas encore testé la ligue des artisans pour voir s'il y avait le même bug.

**Comment by kylaora** [comment]
Problème réglé avec la livraison du 30/04/2020
