### ISSUE TITLE
Mining - 1 ore par coup

### ISSUE THREAD

**Issue by Arafinw** [ariafrance/bugs#76]
Peu importe la compétance ou le type de pioche utilisé, on reçoit 1 ore pour chaque coup de pioche.

100% mining , Pioche en Obsidian toutes les sortes de matériaux miné (ore, copper, cobalt, etc)

![image](https://user-images.githubusercontent.com/65816753/82731623-4acb6700-9cd6-11ea-9970-26e7c63a8e88.png)

**Comment by kylaora** [comment]
Correctif pousser à mettre en place

**Comment by Arafinw** [comment]
Modification fonctionne
