### ISSUE TITLE
[BUG] Message en trop sur le domptage

### ISSUE THREAD

**Issue by kylaora** [ariafrance/bugs#8]
**Description du bug**
Un message : Vous n'avez quasiment aucune chance de dompter cet animal" apparait même lors de la réussite du domptage
**Reproduction du bug**
Réussir a dompter un animal alors que le skill est juste 

**Comportement attendu**
Le message doit apparaitre lors des échecs mais pas à la réussite

**Comment by sirchojin** [comment]
Erreur de traduction+ texte anglais moisi.
