### ISSUE TITLE
[BUG] Panneau charactere Affichage Slots créatures non fonctionnel

### ISSUE THREAD

**Issue by kylaora** [ariafrance/bugs#9]
**Description du bug**
Dans le panneau gauche du personnage. Slots créatures annonce 1/5 quelque soit le nombre de créatures tamé

**Reproduction du bug**
Tamer plus d'un créature et verifier

**Comportement attendu**
Affichage du nombre de créature tamées/5
**Captures d'écran**
[https://screenpresso.com/=hy18e](url)

**Comment by sirchojin** [comment]
Corrigé
